version: '3.8'
services:
  gateway-server:
    image: node:18
    working_dir: /app
    volumes:
      - ./gateway-server:/app
    command: ["npm", "start"]
    ports:
      - "3001:3001"

  auth-server:
    image: node:18
    working_dir: /app
    volumes:
      - ./auth-server:/app
    command: ["npm", "start"]
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - gateway-server

  event-server:
    image: node:18
    working_dir: /app
    volumes:
      - ./event-server:/app
    command: ["npm", "start"]
    ports:
      - "3003:3003"
    depends_on:
      - gateway-server

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      # NOTE: .env 파일이 같은 디렉토리에 있다면 자동으로 값을 읽어온다.
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo-data:
